name = "FinSetsForCAP"
uuid = "0a079e9b-4bc2-44fe-a89b-7607e4464786"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>", "Julia Mickisch <julia.mickisch@student.uni-siegen.de>", "Fabian Zickgraf <f.zickgraf@dashdos.com>"]
version = "0.1.5"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
CartesianCategories = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"
Toposes = "36a15fe6-6211-457f-8fdb-aa2e0d2f3052"

[compat]
CAP = "0.1, 0.2, 0.3, 0.4"
CartesianCategories = "0.1"
Toposes = "0.1"
julia = "1.11"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
